project:
  type: website

website:
  title: "Xinran Li"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: index.qmd#about
      - text: Projects
        href: projects.qmd  
      - text: Experience
        href: index.qmd#experience
      - text: CV
        href: index.qmd#cv
      - text: Contact
        href: index.qmd#contact

format:
  html:
    page-layout: full
    css: styles.css
    toc: false
